-- Migration: 0021_seed_permissions (LEGACY — VÔ HIỆU HÓA)
-- ============================================================
-- FIX (2026-08-31): File seed permission thế hệ cũ. Nó INSERT vào `sec_permissions`
--   với cột lowercase (resource/action) trong khi ở vị trí 0021 `sec_permissions` là
--   BẢNG base dump (cột UPPERCASE RESOURCE_TYPE/ACTION) -> lỗi 1054 "Unknown column 'resource'".
--   Ngoài ra toàn bộ lớp bảng short-name sẽ bị 9000_drop_legacy xóa.
--
--   Bảng quyền CANONICAL là diab_his_sec_permissions (tạo ở 9001_create_sec_all.sql).
--   Toàn bộ permission + mapping role->permission đã được seed ĐẦY ĐỦ vào bảng canonical
--   bởi lớp 90xx (9066_seed_all_gated_permissions, 9054/9063/9064_seed_*_permissions...).
--   Đã VERIFY trên DB dựng sạch: 180 permissions + 296 role-permission mappings, bao gồm
--   mọi mã quyền mà file này định seed (patient.read, prescription.create, ...).
--
--   => Để no-op có chủ đích nhằm giữ thứ tự apply và tránh lỗi. KHÔNG khôi phục nội dung cũ.
--   Xem db/migrations/APPLY_ORDER.md mục "Nhóm đã sửa / superseded".
-- ============================================================
SELECT '0021_seed_permissions: no-op (superseded by 90xx canonical permission seeds)' AS note;
