-- Migration: 0063_seed_pharmacy_stock (LEGACY DEMO — VÔ HIỆU HÓA)
-- ============================================================
-- FIX (2026-08-31): File seed DEMO 30 lô tồn kho vào bảng short-name pha_warehouses / pha_stocks.
--   Ở vị trí 0063, pha_warehouses là bảng base (UPPERCASE, KHÔNG có cột lowercase is_active)
--   -> lỗi 1054 "Unknown column 'is_active'". Hơn nữa các bảng short-name này bị 9000_drop_legacy
--   XÓA và tái tạo ở lớp 90xx (9026_create_pha_warehouses...), nên mọi dữ liệu seed ở đây đều bị hủy.
--
--   Dữ liệu tồn kho DEMO đã được seed vào bảng CANONICAL bởi 9020_seed_rich_demo.sql
--   ("30+ lô tồn kho với trạng thái hết hạn khác nhau"). Vì vậy file này để no-op.
--   Nếu cần seed lại stock demo theo schema mới, tạo file 90xx chạy SAU 9026. Xem APPLY_ORDER.md.
-- ============================================================
SELECT '0063_seed_pharmacy_stock: no-op (demo stock da seed canonical o 9020_seed_rich_demo)' AS note;
