-- ============================================================
-- Migration: 9066_seed_all_gated_permissions
-- Muc dich: dam bao TOAN BO quyen ma backend gate (RequirePermission)
--   ton tai trong diab_his_sec_permissions + cap HET cho role 'admin'.
--   Nhieu seed permission cu fail (cot module/updated_at khong ton tai,
--   role code UPPERCASE) -> prod thieu 42/138 quyen -> FE Can an nut.
-- Danh sach lay tu: git grep RequirePermission trong Controllers.
-- Idempotent: YES (INSERT IGNORE theo code + NOT EXISTS khi grant).
-- ============================================================
SET NAMES utf8mb4;

-- 1. Seed moi quyen backend gate (id=UUID, resource/action tach tu code)
INSERT IGNORE INTO diab_his_sec_permissions (id, code, resource, action, description, created_at)
SELECT UUID(), t.code, SUBSTRING_INDEX(t.code, '.', 1), SUBSTRING(t.code, LOCATE('.', t.code)+1), t.code, NOW()
FROM (
    SELECT 'ai.suggest' AS code
    UNION ALL SELECT 'api_partner.admin'
    UNION ALL SELECT 'api_partner.read'
    UNION ALL SELECT 'api_partner.write'
    UNION ALL SELECT 'appointment.read'
    UNION ALL SELECT 'appointment.write'
    UNION ALL SELECT 'audit.export'
    UNION ALL SELECT 'audit.review'
    UNION ALL SELECT 'bhyt.export'
    UNION ALL SELECT 'bhyt.generate'
    UNION ALL SELECT 'bhyt.read'
    UNION ALL SELECT 'bhyt.reconcile'
    UNION ALL SELECT 'bhyt.sign'
    UNION ALL SELECT 'bhyt.submit'
    UNION ALL SELECT 'bhyt.validate'
    UNION ALL SELECT 'billing.apply_bhyt'
    UNION ALL SELECT 'billing.create'
    UNION ALL SELECT 'billing.finalize'
    UNION ALL SELECT 'billing.print'
    UNION ALL SELECT 'billing.read'
    UNION ALL SELECT 'billing.update'
    UNION ALL SELECT 'billing.void'
    UNION ALL SELECT 'cashier.debt_view'
    UNION ALL SELECT 'cashier.print_receipt'
    UNION ALL SELECT 'cashier.report'
    UNION ALL SELECT 'cashier.shift_close'
    UNION ALL SELECT 'cashier.shift_open'
    UNION ALL SELECT 'cdss.admin'
    UNION ALL SELECT 'cdss.override'
    UNION ALL SELECT 'cdss.read'
    UNION ALL SELECT 'cls_upload.create'
    UNION ALL SELECT 'cls_upload.delete'
    UNION ALL SELECT 'cls_upload.read'
    UNION ALL SELECT 'dashboard.read'
    UNION ALL SELECT 'ddi.check'
    UNION ALL SELECT 'diabetes.assess'
    UNION ALL SELECT 'dispense.perform'
    UNION ALL SELECT 'dispense.queue'
    UNION ALL SELECT 'dispense.reject'
    UNION ALL SELECT 'dispense.return'
    UNION ALL SELECT 'drug.import'
    UNION ALL SELECT 'drug.read'
    UNION ALL SELECT 'drug.sync'
    UNION ALL SELECT 'drug.write'
    UNION ALL SELECT 'dtqg.admin'
    UNION ALL SELECT 'dtqg.retry'
    UNION ALL SELECT 'dtqg.submit'
    UNION ALL SELECT 'einvoice.cancel'
    UNION ALL SELECT 'einvoice.issue'
    UNION ALL SELECT 'einvoice.read'
    UNION ALL SELECT 'emr.export'
    UNION ALL SELECT 'emr.read'
    UNION ALL SELECT 'emr.sign'
    UNION ALL SELECT 'emr.unsign'
    UNION ALL SELECT 'emr.write'
    UNION ALL SELECT 'emr_template.read'
    UNION ALL SELECT 'emr_template.write'
    UNION ALL SELECT 'encounter.close'
    UNION ALL SELECT 'encounter.create'
    UNION ALL SELECT 'encounter.read'
    UNION ALL SELECT 'encounter.start'
    UNION ALL SELECT 'encounter.update'
    UNION ALL SELECT 'encryption.rotate'
    UNION ALL SELECT 'fhir.read'
    UNION ALL SELECT 'file.delete'
    UNION ALL SELECT 'file.upload'
    UNION ALL SELECT 'lab_integration.retry'
    UNION ALL SELECT 'lab_integration.send'
    UNION ALL SELECT 'lab_order.create'
    UNION ALL SELECT 'lab_order.delete'
    UNION ALL SELECT 'lab_order.read'
    UNION ALL SELECT 'lab_order.update'
    UNION ALL SELECT 'lab_partner.admin'
    UNION ALL SELECT 'lab_partner.read'
    UNION ALL SELECT 'lab_partner.write'
    UNION ALL SELECT 'lab_result.import'
    UNION ALL SELECT 'lab_result.read'
    UNION ALL SELECT 'lab_result.verify'
    UNION ALL SELECT 'lab_result.write'
    UNION ALL SELECT 'notification.config'
    UNION ALL SELECT 'notification.read'
    UNION ALL SELECT 'notification.send'
    UNION ALL SELECT 'patient.delete'
    UNION ALL SELECT 'patient.read'
    UNION ALL SELECT 'patient.write'
    UNION ALL SELECT 'payment.collect'
    UNION ALL SELECT 'payment.read'
    UNION ALL SELECT 'payment.refund'
    UNION ALL SELECT 'payment.void'
    UNION ALL SELECT 'payment_qr.generate'
    UNION ALL SELECT 'prescription.cancel'
    UNION ALL SELECT 'prescription.create'
    UNION ALL SELECT 'prescription.read'
    UNION ALL SELECT 'prescription.sign'
    UNION ALL SELECT 'prescription.update'
    UNION ALL SELECT 'rad_order.create'
    UNION ALL SELECT 'rad_order.delete'
    UNION ALL SELECT 'rad_order.read'
    UNION ALL SELECT 'rad_order.update'
    UNION ALL SELECT 'rad_result.read'
    UNION ALL SELECT 'rad_result.verify'
    UNION ALL SELECT 'rad_result.write'
    UNION ALL SELECT 'recall.manage'
    UNION ALL SELECT 'recall.read'
    UNION ALL SELECT 'reception.checkin'
    UNION ALL SELECT 'reception.queue.manage'
    UNION ALL SELECT 'reception.rooms.read'
    UNION ALL SELECT 'reception.stats.read'
    UNION ALL SELECT 'report.build'
    UNION ALL SELECT 'report.export'
    UNION ALL SELECT 'report.read'
    UNION ALL SELECT 'risk.read'
    UNION ALL SELECT 'role.read'
    UNION ALL SELECT 'role.write'
    UNION ALL SELECT 'room.delete'
    UNION ALL SELECT 'room.read'
    UNION ALL SELECT 'room.write'
    UNION ALL SELECT 'service.read'
    UNION ALL SELECT 'service.write'
    UNION ALL SELECT 'service_package.read'
    UNION ALL SELECT 'service_package.write'
    UNION ALL SELECT 'stock.adjust'
    UNION ALL SELECT 'stock.read'
    UNION ALL SELECT 'supplier.read'
    UNION ALL SELECT 'supplier.write'
    UNION ALL SELECT 'system.config'
    UNION ALL SELECT 'tenant.read'
    UNION ALL SELECT 'tenant.write'
    UNION ALL SELECT 'user.assign_role'
    UNION ALL SELECT 'user.delete'
    UNION ALL SELECT 'user.invite'
    UNION ALL SELECT 'user.read'
    UNION ALL SELECT 'user.write'
    UNION ALL SELECT 'vital_sign.delete'
    UNION ALL SELECT 'vital_sign.read'
    UNION ALL SELECT 'vital_sign.write'
    UNION ALL SELECT 'warehouse.read'
    UNION ALL SELECT 'warehouse.write'
) AS t;

-- 2. Cap TOAN BO quyen trong catalog cho role admin (super user)
INSERT INTO diab_his_sec_role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM diab_his_sec_roles r
CROSS JOIN diab_his_sec_permissions p
WHERE r.code = 'admin' AND r.tenant_id IS NULL
  AND NOT EXISTS (SELECT 1 FROM diab_his_sec_role_permissions rp
                  WHERE rp.role_id = r.id AND rp.permission_id = p.id);
